### ISSUE TITLE
High Sponsors

### ISSUE THREAD

**Issue by androiddeveloperdays** [androiddeveloperdays/addwebsite#9]
We need to display Platinium,gold and silver sponsors on top of page similar to old web site.
You may put them above Android Developer Days 2015 title.

**Comment by ozasadnyy** [comment]
Just add `showIndex: true` to corresponding sponsors. Like this:

```
- 
  group: "Platinum"
  showIndex: true   //It would be displayed on index page
  elements: 
    - {name: "CyanogenMod", description: "Android Community Operating System", link: "http://www.cyanogenmod.org/", imageUrl: "cyanogenmod.png"}
    - {name: "4pps", description: "4pps", link: "http://4pps.co/", imageUrl: "4pps.png"}
```

This wouldn't be displayed: 

```
- 
  group: "Book sponsors"
  elements: 
    - {name: "Abaküs Kitap", description: "Abaküs Kitap", link: "http://www.abakuskitap.com/tr", imageUrl: "abakus.jpg"}
    - {name: "Smashing Magazine", description: "For Professional Web Designers and Developers", link: "http://www.smashingmagazine.com/", imageUrl: "smashing-conference.png"}

```
